server:
  port: 8089
spring:
  application:
    name: springboot_redis
  redis:
    host: 42.193.98.249
    port: 6379
    database: 0
    password: redis

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-user?serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: com/baizhi/mapper/*.xml
  type-aliases-package: com/baizhi/entity

#  日志
logging:
  level:
    root: info
    com.baizhi: debug